title: haganenoekigakusha
subtitle: A biologist's attempt at learning something about public health.
author: Delbert Yip
email: delbert124@gmail.com
description: A biologist's attempt at learning something about public health. 
baseurl: "haganenoekigakusha"
url: "https://haganenoneko.github.io/haganenoekigakusha/"

# Build settings
show_excerpts: true
plugins:
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-feed

permalink: /blog/:year/:month/:day/:title/

oscailte:
  #google_analytics: UA-36133007-3
  social:
    github: haganenoneko
    twitter: "@ydhaganeno"
    #rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - index.md
 - about.md
